### ISSUE TITLE
Create D3 Stacked Bar Chart showing Vigorous Exercise Counts vs. Age

### ISSUE THREAD

**Issue by ztraboo** [ztraboo/cpsc-6030-course-project#12]
**Update 1**
Using the Tableau design, we'll need to create this in D3JS.

![image](https://github.com/user-attachments/assets/258c2b34-b92a-4199-bd7a-50439f76df9a)

**Update 2**
Group participants by age group.
> Under 18, 18-24 years old, 25-34 years old, 35-44 years old, 45-54 years old, 55-64 years old, 65+ years old.

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/1d056377-659b-410e-96e9-9656499ebed4">

**Comment by srushtitikekar** [comment]
**Update 1 Results**
<img width="1305" alt="Screenshot 2024-11-11 at 3 26 12 PM" src="https://github.com/user-attachments/assets/7a8f319f-9174-4945-9966-8d7864624ea6">

Changes:
https://github.com/ztraboo/cpsc-6030-course-project/blob/feature/srushtitikekar/create-scatter-plot-health-measure-vs-bmi/D3/plot-stacked-bar.js

**Comment by srushtitikekar** [comment]
Stacked bar chart for Vigorous and Non vigorous exercise by Age Group. 

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/a1c7c032-0324-4fdb-8f65-44fc1dce91d4">

Changes:
https://github.com/ztraboo/cpsc-6030-course-project/commit/1a4b9abc4fdc1af7267b9304a06c38df9f9d0862
