### ISSUE TITLE
Interactivity: Stacked Bar Chart (Physical Workout vs. Age)

### ISSUE THREAD

**Issue by ztraboo** [ztraboo/cpsc-6030-course-project#23]
- [x] Create a selection by age group. Dim out non-selected age-groups. (Acheme)
- [x] When selecting an age group or even exercise-level (vigorous, no) within the group change the Blood Measures vs. BMI scatterplots to filter out dots that are not in that group. (Srushti)
- [x] When selecting an age group or even exercise-level (vigorous, no) within the group change the Waist Circumference vs. BMI scatterplots to filter out dots that are not in that group. (Zachary)
- [x] When selecting an age group or even exercise-level (vigorous, no) within the group change the Donut Gender chart updates it's percentage values and total participant count. (Zachary)

**Comment by srushtitikekar** [comment]
**Interconnectivity of Scatter plot and Bar chart**

1. Each bar in the bar chart has a click event listener. When you click a bar, a custom event called ageGroupSelected is dispatched. This event contains: The selected age group (e.g., 18-34, 35-59). The selected exercise type (e.g., "No" or "Vigorous").
2. The scatter plot listens for the ageGroupSelected event using the window.addEventListener() function. When the event is received, the scatter plot filters its dataset based on the ageGroup and exerciseType values passed in the event.
3. The point rendering of the scatter plot is now enclosed in a function renderScatterPlot(filteredData) which is responsible for rendering points based on the filteredData passed from the Java Script event.

![Screen Recording 2024-11-22 at 11 29 51 AM](https://github.com/user-attachments/assets/c114f2dd-8351-4886-be08-2aa7a78f01b8)

**Comment by ztraboo** [comment]
**Final Output Showing Selection by Exercise Level and Age Group**

![Image](https://github.com/user-attachments/assets/61774aed-142c-4aac-8876-c6eec1562325)
