### ISSUE TITLE
Interactivity: Three Scatterplot (Blood Measures vs. BMI)

### ISSUE THREAD

**Issue by ztraboo** [ztraboo/cpsc-6030-course-project#24]
- [x] When selecting the legend swatch make sure that all three charts change to show selected group.
- [x] When clicking an individual dot perform the following actions.
  - [x] Change radial thickness or color to show dots in other scatterplot charts for association.
  - [x] Have a line link the dots and dim the other points. (If time permitting).

**Interaction Mockup of Selecting One Dot**
![Image](https://github.com/user-attachments/assets/e7b5ac9d-5516-4d85-9a7c-cda5e47104ff)

**Comment by srushtitikekar** [comment]
**Implemented association of the scatter plot points across three graphs.**


![Image](https://github.com/user-attachments/assets/3d58035b-c34e-4cfe-9304-fbf71dde0f02)

**Comment by srushtitikekar** [comment]
![Screen Recording 2024-11-21 at 3 47 13 PM](https://github.com/user-attachments/assets/939e8c32-8c03-47b2-84de-a55194cfbedd)

**Comment by ztraboo** [comment]
Code changes merged: https://github.com/ztraboo/cpsc-6030-course-project/pull/33

![blood-measures-vs-bmi-interaction-on-point-click](https://github.com/user-attachments/assets/7e0f88ff-902e-4820-8bbe-e5a8bec6e03c)
